current: test
env:
  test:
    "com.sankuai.inf.hulk.registryapi": "registryapionline.inf.test.sankuai.com"
    "com.sankuai.inf.hulk.pierui": "pierui.inf.test.sankuai.com"
  dev:
    "com.sankuai.inf.hulk.registryapi": "registryapionline.inf.dev.sankuai.com"
    "com.sankuai.inf.hulk.pierui": "pierui.inf.dev.sankuai.com"