current: test
env:
  test:
    "com.xxx.xxx.xxx.xxx": "xxx.xxx.test.com"
    "com.xxx.xxx.xxx.xxx1": "model1.xxx.test.xxx.com"
  dev:
    "com.xxx.xxx.xxx.xxx": "xxx.xxx.dev.com"
    "com.xxx.xxx.xxx.xxx1": "model1.xxx.dev.xxx.com"